### ISSUE TITLE
タイポ修正

### ISSUE THREAD

**Issue by sshono1210** [chatbox-inc/cb_member2018#74]
https://members.chatbox-inc.com/ の「スキルアップ施策」

## 1. 「コミュニケーション能力の育成」

![screen shot 2018-03-16 at 15 51 27](https://user-images.githubusercontent.com/16553978/37507463-ecadcb96-2931-11e8-9dff-fbab3821cf89.png)

スクショの2行目
「働きすさ」を **「働きやすさ」** に修正

## 2. 「自己管理能力の向上」

![screen shot 2018-03-16 at 15 54 44](https://user-images.githubusercontent.com/16553978/37507548-630adc98-2932-11e8-8d77-fa972194e17f.png)

スクショの1~2行目について、以下のように修正

> 修正前： `Backlogなどのプロジェクト管理ツールBacklogを使った` タスク管理
> 
> 修正後： `Backlogなどのプロジェクト管理ツールを使った` タスク管理

**Comment by mikakane** [comment]
master 宛で PR お願いします。
